### PR TITLE
feat: update RxJS to version 6.x

### PR DESCRIPTION
**Pull request by Koslun**
Update all RxJS imports to use the new import paths for version 6. Breaks any app using RxJS version 5.x. Including any Angular version 5.x user whom would also need to use `rxjs-compat` together with RxJS version 6, since Angular 5 uses RxJS 5.

Closes issue #439

As this contains a breaking change I think it should only be included in the next major version of this library, i.e. version 5.0.0. At least to be compliant with semantic versioning.

I'm a bit uncertain of the exact procedure for changing the library version but assumed that I should leave it out of this PR.

As Angular 6 was working in other ways except for the RxJS dependency I avoided upgrading Angular and other Angular dependencies in this PR. To avoid forcing users to needlessly upgrade to Angular 6, though I think most should, if their dependencies allow for it.

### CODE REVIEW

**Comment by Koslun** [comment]
Forgot that as we're still using Angular 5 in this PR, we need to include `rxjs-compat` for it to work it to work in the tests.

May be noted that as RxJS and Angular are peer dependencies this shouldn't matter for deployment. It only allows for the continued usage of Angular 5.

Updating and testing locally, will update PR once working locally.

**Comment by jkuri** [comment]
hi Adam, thanks alot for this upgrade! Is it ready to merge?

**Comment by jkuri** [comment]
published `4.3.0` on npm.

**Comment by Koslun** [comment]
@jkuri thanks! Updated my example app and verified that it worked there as well: https://github.com/Koslun/ng-example-app/tree/ng6-uploader

As I mentioned above though I would still recommend bumping all the way up to 5.0.0 as this will break anyone still using RxJS 5.x for their app. Breaking expectations of what a 4.2 -> 4.3 bump means which I think might in turn mean time wasted in creating issues in this repository.

Your thoughts?

**Pull request merged**
