### PR TITLE
Enhance/fix docu

### PR DESCRIPTION
**Pull request by osahner**

### CODE REVIEW

**Comment by jkuri** [comment]
thank you. can you also sign the cla please?

**Comment by osahner** [comment]
done

**Comment by jkuri** [comment]
hmmm, I cannot see it:
screen shot 2018-06-19 at 13 53 54

**Comment by osahner** [comment]
I see - the pr was published with my work email address. Just added to it github

**Comment by jkuri** [comment]
I still cannot see cla is signed, maybe you would need to sign it again. nevermind thanks for this PR, merging it now :)

**Pull request merged**
