### PR TITLE
Remove .vscode from repo

### PR DESCRIPTION
**Pull request by leocaseiro**
Hi, I believe it would be nice removing the vscode files from the repo. Specially for npm

### CODE REVIEW

**Comment by karlhiramoto** [comment]
+1

**Comment by schwamster** [comment]
@leocaseiro i agree that it should not be in the npm package but it should be part of the dev-project. so i would instead change .npmignore

**Comment by leocaseiro** [comment]
I don't mind if you prefer to set it on `.npmignore` instead of `.gitignore`, as much as I believe it shouldn't be on npm, I also disagree that should have any IDE/Editor settings on git.

I believe we shouldn't never force a contributor to use the same IDE/Editor. The developer should choose wherever he/she is familiar with. Can be even a simple notepad.

That's why tools such as gulp, grunt, webpack and so on are part of most of building process, instead of forcing an IDE to do this job.

Well, as much as I don't see any hidden files on node_modules, I'm happy anyway 😄

**Comment by schwamster** [comment]
i agree with you that it should not force contributors to use a specific IDE. But the vscode files do not do that. All they are doing is providing additional support to contributors that are using VSC.  In this particular case they just make sure that the compile errors of VSC are consistent with the typescript version used => https://code.visualstudio.com/Docs/languages/typescript#_using-newer-typescript-versions
I might be missing something though...

**Comment by leocaseiro** [comment]
Hi @schwamster. Thanks for letting me know. I wasn't aware of that.
O normally use .tsconfig and I thought that would be enough for vscode as well.

**Pull request closed without merging**
